
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Dec  2 2025 18:02:12 MSK (Dec  2 2025 15:02:12 UTC)

// Verification Directory fv/muxed_delays 

module muxed_delays(delay_lines, select, out);
  input [3:0] delay_lines;
  input [1:0] select;
  output out;
  wire [3:0] delay_lines;
  wire [1:0] select;
  wire out;
  wire n_0;
  MUX3V1_140P9T30R g89__2398(.I0 (delay_lines[0]), .I1
       (delay_lines[2]), .I2 (n_0), .S0 (select[1]), .S1 (select[0]),
       .Z (out));
  MUX2CV2_140P9T30R g90__5107(.I0 (delay_lines[1]), .I1
       (delay_lines[3]), .S (select[1]), .Z (n_0));
endmodule

