
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Dec 30 2025 13:38:30 MSK (Dec 30 2025 10:38:30 UTC)

// Verification Directory fv/const_delay 

module const_delay(I, O);
  input I;
  output O;
  wire I;
  wire O;
  wire \delay_buf[1] , \delay_buf[2] , \delay_buf[3] , \delay_buf[4] ;
  DEL4V4_140P9T30R \DELAY_STAGES[0].u_delay_inst (.I (I), .Z
       (\delay_buf[1] ));
  DEL4V4_140P9T30R \DELAY_STAGES[1].u_delay_inst (.I (\delay_buf[1] ),
       .Z (\delay_buf[2] ));
  DEL4V4_140P9T30R \DELAY_STAGES[2].u_delay_inst (.I (\delay_buf[2] ),
       .Z (\delay_buf[3] ));
  DEL4V4_140P9T30R \DELAY_STAGES[3].u_delay_inst (.I (\delay_buf[3] ),
       .Z (\delay_buf[4] ));
  DEL4V4_140P9T30R \DELAY_STAGES[4].u_delay_inst (.I (\delay_buf[4] ),
       .Z (O));
endmodule

